# Generated by Django 3.2.7 on 2021-11-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roblox',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('universeid', models.TextField(blank=True, null=True)),
                ('placeid', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('allowedgeargenres', models.TextField(blank=True, null=True)),
                ('isgenreenforced', models.BooleanField(blank=True, null=True)),
                ('isallgenre', models.BooleanField(blank=True, null=True)),
                ('playing', models.IntegerField(blank=True, null=True)),
                ('visits', models.TextField(blank=True, null=True)),
                ('favoritedcount', models.IntegerField(blank=True, null=True)),
                ('gamerating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roblox',
                'managed': False,
            },
        ),
    ]
